# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-CRvJJlf0Z2moAsAF8zzui10XZHeYct
"""

from logic import MBTITest
from questions import questions


def main():
    """نقطه شروع برنامه MBTI"""
    test = MBTITest(questions)
    test.conduct_test()


if __name__ == "__main__":
    main()
